### ISSUE TITLE
pharmacy.json 药房数据不足啊

### ISSUE THREAD

**Issue by FC0511** [542154968/getHfMask#1]
pharmacy.json 药房数据不足啊

**Comment by 542154968** [comment]
已更新~
---------------------------------------
 如果您不知道您要领取的药店的名称和编号，请点击`getPharmacy.js`，在第二行`pharmacyName`处输入您想查询的药房名称，然后执行`node getPharmacy.js`即可查阅到相关信息。药房数据格式请查阅`common/pharmacy.json`，其中每个数据的`name`值，即为药店名称，其`code`就是药店的编号ID。或者[在此查询](http://kzgm.bbshjz.cn:8000/ncms/mask/pharmacy-list)，其中编号ID可以通过审查元素或者接口信息中看到。

----------------------------------------
另外 在这里占用几个图 嘻嘻


![QQ图片20200207171602](https://user-images.githubusercontent.com/25705659/74017778-c9262680-49cf-11ea-8a8e-4e45fdb3b708.png)
![QQ图片20200207171608](https://user-images.githubusercontent.com/25705659/74017784-caefea00-49cf-11ea-901e-2a99b504d500.jpg)
![QQ截图20200207172323](https://user-images.githubusercontent.com/25705659/74017789-cb888080-49cf-11ea-9f30-a08fe34abb7d.jpg)
