### ISSUE TITLE
能否加上多用户支持？

### ISSUE THREAD

**Issue by moxia** [542154968/getHfMask#10]
userData.js里配置多个人的信息，多线程运行，预约口罩。

**Comment by zc910704** [comment]
这个改起来不难，可以自己尝试下，但是接口有限制，不清楚内部具体逻辑，如果这样我怀疑很可能每个都抢不到。

**Comment by 542154968** [comment]
自己多拷贝几个项目就行啦 。。但是没必要搞很多用户 对方有IP检测（猜测）同时间段请求量多了会给你封住一段时间，就是报你请求频繁，到时候得不偿失呀。。

**Comment by moxia** [comment]
@zc910704 @542154968 嗯，昨天拷贝了一个项目，一次性成功抢了10个口罩，nodejs不是很熟悉，我看源码里有通过IP代理处理同一个IP多次请求限制的逻辑，那我去找些稳定的IP代理，今天准备抢20个。。

**Comment by zc910704** [comment]
> 自己多拷贝几个项目就行啦 。。但是没必要搞很多用户 对方有IP检测（猜测）同时间段请求量多了会给你封住一段时间，就是报你请求频繁，到时候得不偿失呀。。

顺便在这问一句 页面里的sojsonv5加密你是如何解密的

**Comment by moxia** [comment]
我也好奇怎么解密sojsonv5的，如果不解密，获取不到验证码图片真正的base64..

**Comment by 542154968** [comment]
阅读源码，推测，实践，大力出奇迹。
那个加密就是高度混淆，因为他们网页用得JQ $没有混淆掉 从$作为出发点，然后找$('xxx').val(xxx)相似的代码，这段代码是用来给表单赋值的。然后发现了hex_md5加密的逻辑 alert值就知道了

**Comment by zc910704** [comment]
> 阅读源码，推测，实践，大力出奇迹。
> 那个加密就是高度混淆，因为他们网页用得JQ $没有混淆掉 从$作为出发点，然后找$('xxx').val(xxx)相似的代码，这段代码是用来给表单赋值的。然后发现了hex_md5加密的逻辑 alert值就知道了

牛逼

**Comment by TMODER** [comment]
> @zc910704 @542154968 嗯，昨天拷贝了一个项目，一次性成功抢了10个口罩，nodejs不是很熟悉，我看源码里有通过IP代理处理同一个IP多次请求限制的逻辑，那我去找些稳定的IP代理，今天准备抢20个。。

我最多抢过15个。。
