### ISSUE TITLE
接入文档

### ISSUE THREAD

**Issue by qingzhuowa2019** [542154968/getHfMask#2]
你好~我想请问一下接入文档具体要如何操作呢

**Comment by 542154968** [comment]
接入什么文档? 百度API?

进入百度云文字识别,然后创建个应用,之后获取到应用的`APP_ID`, `API_KEY`, `SECRET_KEY`。将这些输入到`common/baidu.js`中。

**Comment by qingzhuowa2019** [comment]
> 接入什么文档? 百度API?
> 进入百度云文字识别,然后创建个应用,之后获取到应用的APP_ID, API_KEY, SECRET_KEY。将这些输入到common/baidu.js中。

谢谢谢谢，不好意思还有个问题，请问用户数据中填写不同的药店名称用什么连接呢

**Comment by 542154968** [comment]
看使用帮助第三条

**Comment by qingzhuowa2019** [comment]
> 看使用帮助第三条

大佬我看了的~主要我小白，不太清楚js的语法，我就是想问问在填写pharmacy name，好几个药店的时候，我用逗号隔开报错，是“药店A,药店B,C.....”， 这样才对么，麻烦您了！为了口罩太南了

**Comment by 542154968** [comment]
只能填一个奥 

```javascript
module.exports = {
    // 姓名
    name: "xxx",
    // 身份证
    cardNo: "xxxx",
    // 手机号
    phone: "xxxx",
    // 口罩数量 固定5 切勿更改
    reservationNumber: "5",
    // 领取口罩的药店名称 该信息可查阅  README.md -> 使用帮助 -> 第三条
    pharmacyName: "国胜大药房坝下路店",
    // 领取口罩的药店编号ID 该信息可查阅  README.md -> 使用帮助 -> 第三条
    pharmacyCode: "11183",
    // 通过上次请求获取到的有效的口罩信息 数量和时间点 请勿填写，自动获取生成
    pharmacyPhase: "",
    // 请勿填写，自动获取生成
    pharmacyPhaseName: "",
    // 验证码 自动获取
    captcha: ""
};
```

**Comment by 542154968** [comment]
那个查询药店的时候根据药店名字或者街道来查。只能输入一个关键字。

1.  比如你要查坝下路的药店 这里就输入
```javascript
// 在此输入您想查询的药房名称，即可获取信息。 ！！！
var pharmacyName = '坝下路'
```

2. 比如你要查药店名称
```javascript
// 在此输入您想查询的药房名称，即可获取信息。 ！！！
var pharmacyName = '国胜大药房'
```

**Comment by qingzhuowa2019** [comment]
> 那个查询药店的时候根据药店名字或者街道来查。只能输入一个关键字。
> 
> 比如你要查坝下路的药店 这里就输入
> 
> // 在此输入您想查询的药房名称，即可获取信息。 ！！！
> var pharmacyName = '坝下路'
> 
> 比如你要查药店名称
> 
> // 在此输入您想查询的药房名称，即可获取信息。 ！！！
> var pharmacyName = '国胜大药房'

奥奥！原来是这样，好嘚，谢谢大佬！
