### ISSUE TITLE
接口改了，必须微信打开链接的才可以。

### ISSUE THREAD

**Issue by TMODER** [542154968/getHfMask#5]
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
</head>
<body>
<div class="page-body">
    <div style="text-align: left; padding: 30px 30px;">
        <span style="font-size:16px; color:#F00;">请使用微信打开！</span>
    </div>
</div>
</body>
</body>
</html>

**Comment by 542154968** [comment]
![微信截图_20200223214013](https://user-images.githubusercontent.com/25705659/75113075-28995d00-5685-11ea-9850-bcc3288cbe33.png)

已更新
