### ISSUE TITLE
大佬，目前通过百度的识图api，会出现识别的验证码错误！

### ISSUE THREAD

**Issue by TMODER** [542154968/getHfMask#7]

**Comment by 542154968** [comment]
28号更新了一版  你现在是那个版本吗  他们天天改。。。------------------ 原始邮件 ------------------
发件人: "TMODER"<notifications@github.com>
发送时间: 2020年3月1日(星期天) 中午12:06
收件人: "542154968/getHfMask"<getHfMask@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [542154968/getHfMask] 大佬，目前通过百度的识图api，会出现识别的验证码错误！ (#7)


 
&mdash;

**Comment by TMODER** [comment]
好的 ==== 大佬 我来试试

**Comment by 542154968** [comment]
我抢到了
![QQ图片20200301170408](https://user-images.githubusercontent.com/25705659/75622739-a823b080-5bde-11ea-8e5a-2eb8e80cae48.png)

**Comment by TMODER** [comment]
好的  我拉去下最新的代码  感谢

**Comment by TMODER** [comment]
好的 我拉取下最新的代码  感谢
