### ISSUE TITLE
一点代码上的疑问

### ISSUE THREAD

**Issue by zc910704** [542154968/getHfMask#8]
感谢楼主的奉献，试着用c#实现了一遍，学到很多。
有些疑问想请教一下。
第一点是common\requestForm.js这里的函数虽然导出了，好像并没有用到，是不是我哪里看错了，如果这里没用到这个函数，那么content-length是node自行管理的么？
第二点是 index.js中
` 
var date = String(new Date().getTime() - config.dateDifference);
        sendData.hash = hex_md5(date + 'c7c7405208624ed90976f0672c09b884')
        sendData.pharmacyPhase = maskObj.value;
        sendData.pharmacyPhaseName = maskObj.text;
        sendData.timestamp = date
 `
1. date变量这里为啥没有取前10位；
2. 'c7c7405208624ed90976f0672c09b884'又是啥
3. sendData中好像并没有定义timestamp 和hash ,这里这两个参数是服务器验证必须的么，不提前定义js会自动创建么？

很久没写js，见谅我的姿势水平。

**Comment by 542154968** [comment]
1. `requestForm` 在`getPharmacy.js`获取药店信息的接口中使用到了。其实这是一个技术栈使用的失误，由于用得原生的`http`，`https`，导致了一些封装复用的问题，于是干脆就抽开。其实使用`request`这个包是比较好的。
2. `date`的取值范围取决于对方接口，我是查阅他们的网页源码发现新增了`timestamp`和`hash`字段，我考虑的是既然这俩字段不需要用户去填，为了避免误导用户，增加复杂度，就没有体现在配置文件上。
3. `c7c7405208624ed90976f0672c09b884`这个是我查阅他们源码发现的他们生成hash的秘钥。hash的生成规则就是 `当前访问时间戳 timestamp` + `秘钥`。在使用md5加密。

**Comment by zc910704** [comment]
明白了
1.因为药房信息已知，requestForm在主代码中其实可以并不需要。
2.这里的timestamp和hash和URL处理里的只取前十位的时间戳是两回事，这是需要post的json中的信息，而且是取全部到毫秒的时间戳。
3.js里json新的字段是可以直接设置的，不需要和export的定义一致。
4.时间戳偏差请教下这里是如何发现的，服务器拿到timestamp生成hash就算是服务器和本地时间不一致应该也是可以校验通过的吧？

**Comment by 542154968** [comment]
1. 是的，只是用在获取药房信息的。
2. 是的，timestamp和hash是后端的接口需要的字段  就只能按照那个格式来 他们的接口规范
3. 那个不是json 是js的`object` js比较灵活，弱类型的，可以随意增删改对象。不像强类型语言，定义好了就不好改动字段了。
4. 这个是我请求老是报请求频繁，排查之后，我试了下查看网页源码上的时间戳，发现那个不报，于是就发现了大概30s的时间偏差，是我的电脑时间慢了。

**Comment by jackcc** [comment]
> 1. 是的，只是用在获取药房信息的。
> 2. 是的，timestamp和hash是后端的接口需要的字段  就只能按照那个格式来 他们的接口规范
> 3. 那个不是json 是js的`object` js比较灵活，弱类型的，可以随意增删改对象。不像强类型语言，定义好了就不好改动字段了。
> 4. 这个是我请求老是报请求频繁，排查之后，我试了下查看网页源码上的时间戳，发现那个不报，于是就发现了大概30s的时间偏差，是我的电脑时间慢了。

那正常使用的时候，这个时间偏差该怎么设置呢？本地的时间就是标准的北京时间

**Comment by zc910704** [comment]
正常就按他的不改就行
